### ISSUE TITLE
appears to require go 1.12 contrary to README

### ISSUE THREAD

**Issue by ferebee** [schollz/croc#146]
If I try to build on go 1.11.5 (installed on SmartOS via pkgsrc), I get an error

`go/src/github.com/schollz/croc/src/cli/cli.go:98:17: undefined: os.UserHomeDir`

This does not occur with go 1.12.5. Is 1.12 a requirement? The README states a requirement for 1.11+.

**Comment by schollz** [comment]
Yeah, I wanted to use ethe `os.UserHomeDir` so I bumped the version needed.
