### ISSUE TITLE
Compilation failed with Go 1.23

### ISSUE THREAD

**Issue by CompuRoot** [schollz/croc#795]
I see that `go.mod` set to `go 1.17`, but just reporting. It looks [like Go 1.23 broke internal symbols](https://github.com/chipmk/docker-mac-net-connect/issues/39#issuecomment-2299898790)

- **Enviroment:** debian 11 x86_64
- **Compile:** `goreleaser build --skip-validate --rm-dist --single-target;`

Failed with error:
```
⨯ build failed after 6s error=failed to build for linux_amd64_v1: exit status 1: # github.com/schollz/croc/v9

link: golang.org/x/net/internal/socket: invalid reference to syscall.recvmsg
```

**Comment by schollz** [comment]
Is this a goreleaser error? 

I'm on Ubuntu 24 and can compile with go1.23
```
> go version && go build -v && ./croc --version
go version go1.23.0 linux/amd64
croc version v10.0.11
```

**Comment by CompuRoot** [comment]
> Is this a goreleaser error?

I'm really sorry for the noise, it looks like my git got screwed on my side, I cloned latest version now from github and everything is good, both with goreleaser and direct compilation works as expected.
